version: '3.7'
services:
  nginx:
    container_name: televoke-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
  server:
    container_name: televoke-server
    image: node:18-alpine
    volumes:
      - ..:/data
    working_dir: /data
    command: ['node', 'examples/network/server.js', '0.0.0.0', '8698', '8080']
  lwdfx-tcp-client-to-server:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - server
    working_dir: /data
    command: ['node', 'examples/network/lwdfx-client.js', 'televoke-server', '8698']
  lwdfx-tcp-client-over-nginx:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - nginx
    working_dir: /data
    command: ['node', 'examples/network/lwdfx-client.js', 'televoke-nginx', '18698']
  legacy-http-client-to-server:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - server
    working_dir: /data
    command: ['node', 'examples/network/legacy-http-client.js', 'televoke-server', '8080']
  legacy-http-client-over-nginx:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - nginx
    working_dir: /data
    command: ['node', 'examples/network/legacy-http-client.js', 'televoke-nginx', '18080']
  ws-client-to-server:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - server
    working_dir: /data
    command: ['node', 'examples/network/ws-client.js', 'televoke-server', '2095']
  ws-client-over-nginx:
    image: node:18-alpine
    volumes:
      - ..:/data
    depends_on:
      - nginx
    working_dir: /data
    command: ['node', 'examples/network/ws-client.js', 'televoke-nginx', '12095']
